services:
  convertx:
    # https://github.com/C4illin/ConvertX
    container_name: convertx
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: convertx
    image: ${CONVERTX_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.convertx.entrypoints=web,websecure"
      - "traefik.http.routers.convertx.rule=Host(`convert.${DOMAIN}`)"
      - "traefik.http.routers.convertx.tls=true"
      # - "traefik.http.routers.convertx.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.convertx.tls.domains[0].main=convert.${DOMAIN}"
      - "traefik.http.routers.convertx.service=convertx"
      # Services
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${CONVERTX_IP}
    ports:
      - 3000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/app/data

networks:
  traefik-net:
    external: true
    name: traefik-net
