# https://github.com/cmintey/wishlist
services:
  wishlist:
    container_name: wishlist
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: wishlist
    image: ${WISHLIST_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.wishlist.entrypoints=web-external,websecure-external"
      - "traefik.http.routers.wishlist.rule=Host(`wish.${DOMAIN}`)"
      - "traefik.http.routers.wishlist.tls=true"
      # - "traefik.http.routers.wishlist.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.wishlist.tls.domains[0].main=wish.${DOMAIN}"
      - "traefik.http.routers.wishlist.service=wishlist"
      # Services
      - "traefik.http.services.wishlist.loadbalancer.server.port=3280"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${WISHLIST_IP}
    ports:
      - 3280
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      # This is where the sqlite database will be stored
      - ./persistence/data:/usr/src/app/data
      # This is where user image uploads will be stored
      - ./persistence/uploads:/usr/src/app/uploads

networks:
  proxy-net:
    external: true
    name: traefik-net
