# General
docker_gid: 1001
docker_uid: 1001
local_domain: false

# Ansible
deb_architecture: { "armv6l": "armhf", "armv7l": "armhf", "aarch64": "arm64", "x86_64": "amd64", "i386": "i386" }

# Docker networks
traefik_net: 192.168.10.0/24
traefik_gateway: 192.168.10.1
dns_net: 192.168.30.0/24
dns_gateway: 192.168.30.1
monitoring_net: 192.168.40.0/24
monitoring_gateway: 192.168.40.1
ai_net: 192.168.210.0/24
ai_gateway: 192.168.210.1

# Services
actual_enable: true
adventurelog_enable: true
affine_enable: true
bytestash_enable: true
change_detection_enable: true
convertx_enable: true
docuseal_enable: true
enclosed_enable: true
freshrss_enable: true
gitlab_enable: true
gokapi_enable: true
grafana_enable: true
grocy_enable: true
guacamole_enable: true
homarr_enable: true
homebox_enable: true
homer_enable: true
home_assistant_enable: true
hortusfox_enable: true
immich_enable: true
it_tools_enable: true
jellyfin_enable: true
jetlog_enable: true
karakeep_enable: true
kavita_enable: true
kopia_enable: true
litellm_enable: true
mathesar_enable: true
minecraft_enable: true
n8n_enable: true
navidrome_enable: true
ntfy_enable: true
obsidian_enable: true
ollama_enable: true
open_webui_enable: true
paperless_enable: true
pihole_enable: true
pinry_enable: true
prometheus_enable: true
rustdesk_enable: true
scrutiny_enable: true
searngx_enable: true
stirling_pdf_enable: true
unbound_enable: true
upsnap_enable: true
vaultwarden_enable: true
wakapi_enable: true
wallos_enable: true
wazuh_enable: false
wireguard_easy_enable: true
wishlist_enable: true

directus_enable: false
firefly_enable: false
librum_enable: false
limesurvey_enable: false
meme_search_enable: false
nextcloud_enable: false
photoprism_enable: false
wireguard_enable: false
