services:
  db:
    container_name: n8n-postgres
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${N8N_DB_USER}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: n8n-postgres
    image: ${DEFAULT_POSTGRES_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${N8N_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./db-persistence:/var/lib/postgresql/data

  n8n:
    # https://github.com/n8n-io/n8n
    container_name: n8n
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: n8n
    image: ${N8N_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.n8n.entrypoints=web,websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)"
      - "traefik.http.routers.n8n.tls=true"
      # - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.n8n.tls.domains[0].main=n8n.${DOMAIN}"
      - "traefik.http.routers.n8n.middlewares=n8n@docker"
      - "traefik.http.routers.n8n.service=n8n"
      # Middlewares
      - "traefik.http.middlewares.n8n.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.n8n.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.n8n.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN}"
      - "traefik.http.middlewares.n8n.headers.SSLRedirect=true"
      - "traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.n8n.headers.STSPreload=true"
      - "traefik.http.middlewares.n8n.headers.STSSeconds=315360000"
      # Services
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${N8N_INTERNAL_IP}
      traefik-net:
        ipv4_address: ${N8N_IP}
    ports:
      - 5678
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/home/node/.n8n
      - ./local-persistence/files:/files

networks:
  app-net:
    name: n8n-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${N8N_NET}
          gateway: ${N8N_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
