# https://github.com/usememos/memos
services:
  db:
    container_name: memos-postgres
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MEMOS_DB_USER}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: memos-postgres
    image: ${DEFAULT_POSTGRES_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${MEMOS_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./db-persistence:/var/lib/postgresql/data

  memos:
    container_name: memos
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: memos
    image: ${MEMOS_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.memos.entrypoints=web,websecure"
      - "traefik.http.routers.memos.rule=Host(`memos.${DOMAIN}`)"
      - "traefik.http.routers.memos.tls=true"
      # - "traefik.http.routers.memos.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.memos.tls.domains[0].main=memos.${DOMAIN}"
      - "traefik.http.routers.memos.service=memos"
      # Services
      - "traefik.http.services.memos.loadbalancer.server.port=5230"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${MEMOS_INTERNAL_IP}
      traefik-net:
        ipv4_address: ${MEMOS_IP}
    ports:
      - 5230
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./memos:/var/opt/memos

networks:
  app-net:
    name: memos-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${MEMOS_NET}
          gateway: ${MEMOS_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
